name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1
          cache-read-only: false

      # ----------------------------------------------------------------------

      - name: Run tests
        run: ./gradlew test

      # ----------------------------------------------------------------------

      - name: Build the project
        run: ./gradlew build

      # ----------------------------------------------------------------------

      - name: Create Debug APK
        run: ./gradlew assembleDebug

      - name: Create Release APK
        run: ./gradlew assemble

      - name: Move APks
        run: |
         mkdir APKs
         mv app/build/outputs/apk/debug/app-debug.apk APKs/Kyrgyz-Keyboard.apk
         mv app/build/outputs/apk/release/app-release-unsigned.apk APKs/Kyrgyz-Keyboard-release.apk

      # ----------------------------------------------------------------------

      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK
          path: APKs/Kyrgyz-Keyboard.apk

      - name: Upload Release APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: APKs/Kyrgyz-Keyboard-release.apk

      # ----------------------------------------------------------------------

      - name: Upload APKs to Cloudflare R2
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: APKs
          destination-dir: ./
