name: Build

on: [push, workflow_dispatch]

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1
          cache-read-only: false

      # ----------------------------------------------------------------------

      - name: Run tests
        run: ./gradlew test

      # ----------------------------------------------------------------------

      - name: Build the project
        run: ./gradlew build

      # ----------------------------------------------------------------------

      - name: Create Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk

      # ----------------------------------------------------------------------

      - name: Create Release APK
        run: ./gradlew assemble

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk
